# Generated by Django 4.2.1 on 2023-06-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_mymodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dostavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=300)),
                ('title', models.CharField(choices=[('hot_dog', 'Hot Dog'), ('lavash', 'Lavash'), ('pitsa', 'Pitsa'), ('burger', 'Burger'), ('donar', 'Donar'), ('sandvich', 'Sandvich')], default=0, max_length=200)),
                ('count', models.PositiveBigIntegerField(blank=True, default=1, null=True)),
                ('price', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('location', models.CharField(choices=[('andijon_tumani', 'Andijon tumani'), ('yangi_bozor', 'Yangi bozor'), ('eski_shahar', 'Eski shahar'), ("o'bekiston_ko'chasi", "O'zbekiston ko'chasi"), ('bobur_kochasi', 'Bobur kochasi'), ("bog'ishamol", "Bog'ishamol")], default=0, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('yetkazib_berilgan', 'Yetkazib berilgan'), ('tayyorlanmoqda', 'Tayyorlanmoqda')], default=0, max_length=200)),
            ],
            options={
                'verbose_name': 'Dostavka',
                'verbose_name_plural': 'Dostavka',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
