# Generated by Django 4.2.1 on 2023-07-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_dostavka_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='dostavka',
            name='all_price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
